#!/usr/bin/env bash
# A scaffolded project tells its agent that skills arrive on their own, and
# leaves exactly one place for the sync to record what arrived.
#
# This replaced a 68-line session-start check that asked the agent to fetch the
# registry, diff it against the installed copies by hand, and offer three apply
# modes. That check existed because nothing else knew a copy had gone stale. The
# SessionStart hook knows, so the prose is not a smaller version of the check -
# it is the check's replacement, and an agent that still runs one is doing work
# the hook already did before it was asked anything.
#
# The marker pair is the load-bearing part. skill-sync writes the installed list
# between the two comments, so a template that ships without them gives the sync
# nowhere to write, and the failure is silent: the sync installs correctly and
# the project's CLAUDE.md simply never says what it holds. Asserting both
# markers, and asserting that scaffold.sh put no table between them, is what
# keeps that ownership where the design put it.
CASE_NAME=140-skills-block
source "${SKILL:-/skill}/testing/assert.sh"

p=$(scaffolded_project)

assert_contains "$p/CLAUDE.md" "## Skills" \
  "CLAUDE.md carries the skills section"

# Nothing to run. The whole point of the replacement is that the agent stops
# performing a check, so the template has to say so rather than say nothing.
assert_contains "$p/CLAUDE.md" "You do not run anything" \
  "the agent is told it runs nothing"

# The one edit that is never safe. A managed skill is gitignored, so a local fix
# looks like it worked, survives review because it is not in any diff, and is
# gone at the next session start with no conflict and no warning.
assert_contains "$p/CLAUDE.md" "Never edit a managed skill in place" \
  "editing a managed copy in place is refused"

assert_contains "$p/CLAUDE.md" ".claude/skills.toml" \
  "the manifest is named as the file to edit"

# Both markers, byte for byte, because skill-sync matches on them. A reworded
# opening comment is not a cosmetic change - it is the sync losing its anchor.
assert_contains "$p/CLAUDE.md" \
  "<!-- skills:begin - generated by skill-sync, do not hand-edit -->" \
  "the generated list opens with the skills:begin marker"

assert_contains "$p/CLAUDE.md" "<!-- skills:end -->" \
  "the generated list closes with the skills:end marker"

# scaffold.sh writes the markers and nothing between them. A table shipped in
# the template is a second source of truth that is wrong the moment the manifest
# changes, and it is wrong in the direction agents believe.
between=$(awk '/skills:begin/ { on = 1; next } /skills:end/ { on = 0 } on' "$p/CLAUDE.md" | tr -d '[:space:]')
assert_eq "" "$between" "scaffold.sh writes no table between the markers"

# Names only, never versions. A hand-maintained version table is wrong within a
# week, and a stale one is worse than none because agents believe it.
assert_not_contains "$p/CLAUDE.md" "| skill            | installed | latest | bump  |" \
  "no hand-maintained version table survives in the template"

# The check this replaced fetched the registry from the agent's own hands. If
# that URL is back in the template, the old flow is back with it.
assert_not_contains "$p/CLAUDE.md" \
  "https://raw.githubusercontent.com/jkkelley/dotfiles/main/claude/skills/registry.json" \
  "the agent is not asked to fetch the registry itself"

finish
