// Job DSL seed script — generates multibranch pipeline jobs from jobs/repos.yaml.
//
// Goes in: jenkins-shared-lib/jobs/seed-job.groovy
// Run by:  jenkins-shared-lib/jobs/seed-pipeline.groovy via the jobDsl() step.
//
// Skill: jenkins-job-bootstrap (~/.claude/skills/jenkins-job-bootstrap/)

import groovy.yaml.YamlSlurper

def reposYaml = readFileFromWorkspace('jobs/repos.yaml')
def config = new YamlSlurper().parseText(reposYaml)
def defaults = config.defaults ?: [:]

def defaultOrg = defaults.github_org ?: '<your-github-username>'
def defaultCred = defaults.scm_credentials_id ?: 'github-pat'
def defaultScript = defaults.script_path ?: 'jenkins/Jenkinsfile'
def defaultBuildsToKeep = (defaults.builds_to_keep ?: 20) as int
def defaultBranchesToKeep = (defaults.branches_to_keep ?: 20) as int
def defaultScanIntervalMin = (defaults.scan_interval_minutes ?: 60) as int

config.repos.each { repo ->
    def repoName = repo.name
    if (!repoName) {
        println "WARN: skipping repo entry with no 'name' field"
        return
    }

    def org = repo.github_org ?: defaultOrg
    def cred = repo.scm_credentials_id ?: defaultCred
    def scriptPath = repo.script_path ?: defaultScript
    def buildsToKeep = (repo.builds_to_keep ?: defaultBuildsToKeep) as int
    def branchesToKeep = (repo.branches_to_keep ?: defaultBranchesToKeep) as int
    def scanIntervalMin = (repo.scan_interval_minutes ?: defaultScanIntervalMin) as int
    def description = repo.description ?: "Auto-generated by jenkins-job-bootstrap skill. Manifest: jenkins-shared-lib/jobs/repos.yaml"

    multibranchPipelineJob(repoName) {
        displayName(repoName)
        description(description)

        branchSources {
            github {
                id("${repoName}-github")
                scanCredentialsId(cred)
                repoOwner(org)
                repository(repoName)
                // Branch discovery: all branches + PRs from origin
                buildOriginBranch(true)
                buildOriginBranchWithPR(true)
                buildOriginPRMerge(true)
                buildOriginPRHead(false)
                buildForkPRMerge(false)
                buildForkPRHead(false)
            }
        }

        factory {
            workflowBranchProjectFactory {
                scriptPath(scriptPath)
            }
        }

        // Cap branches per multibranch job
        orphanedItemStrategy {
            discardOldItems {
                numToKeep(branchesToKeep)
            }
        }

        // Cap builds per branch
        configure { node ->
            def traits = node / sources / data / 'jenkins.branch.BranchSource' / source / traits
            // (traits stanza populated by the github { } block above; configure block reserved
            //  for future per-repo customizations)

            def properties = node / properties
            properties << 'jenkins.branch.NoTriggerOrganizationFolderProperty'()
        }

        // Periodic re-scan in case webhook misfires
        triggers {
            periodicFolderTrigger {
                interval("${scanIntervalMin}m")
            }
        }
    }

    println "Generated multibranchPipelineJob: ${repoName} (org=${org}, cred=${cred}, script=${scriptPath})"
}

println "seed-job.groovy: processed ${config.repos.size()} repo(s)"
